DBP-351- Helm chart deployment job runs even if the Trivy scan fails

diff --git a/.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml b/.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
--- a/.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
+++ b/.github/workflows/image-and-helm-publish-check-deploy-on-push-scheduled.yml
@@ -99,7 +99,7 @@ jobs:
               echo "SELECT_IMAGE_TAG_GENERATION=ticket_from_branch" >> "$GITHUB_OUTPUT"
           fi
   release_helm:
-    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@2.1.1
+    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@3.0.1
     needs: 
       - select_helm_version_generation
     secrets: inherit
@@ -120,12 +120,13 @@ jobs:
       branch: ${{ needs.branch_meta.outputs.branch }}
 
   deploy:
-    if: ${{ github.event_name == 'push' && !startsWith(github.ref_name,'dependabot/') && (success() || failure()) }}
+    #if: ${{ github.event_name == 'push' && !startsWith(github.ref_name,'dependabot/') && (success() || failure()) }}
+    if: ${{ github.event_name == 'push' && !startsWith(github.ref_name,'dependabot/') }}
     needs:
       - branch_meta
       - create_branch_identifier
       - release_helm
-      - build_image_on_push
+      #- build_image_on_push
     uses: dBildungsplattform/spsh-app-deploy/.github/workflows/deploy.yml@main
     with:
       dbildungs_iam_server_branch: main
